apiVersion: apps/v1
kind: Deployment
metadata:
  name: nivora-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nivora-server
  template:
    metadata:
      labels:
        app: nivora-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: server
          image: sevoniva/nivora:0.1.0-dev
          args: ["server", "--config", "/etc/nivora/server.yaml"]
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /etc/nivora
              readOnly: true
            - name: objectstore
              mountPath: /var/lib/nivora/objectstore
      volumes:
        - name: config
          configMap:
            name: nivora-config
        - name: objectstore
          emptyDir: {}
