apiVersion: apps/v1
kind: Deployment
metadata:
  name: nivora-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nivora-worker
  template:
    metadata:
      labels:
        app: nivora-worker
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: worker
          image: sevoniva/nivora:0.1.0-dev
          args: ["worker", "--config", "/etc/nivora/worker.yaml"]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /etc/nivora
              readOnly: true
            - name: objectstore
              mountPath: /var/lib/nivora/objectstore
      volumes:
        - name: config
          configMap:
            name: nivora-config
        - name: objectstore
          emptyDir: {}
