{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nivora.fullname" . }}-secret
  labels:
    {{- include "nivora.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.stringData }}
  {{- toYaml .Values.secret.stringData | nindent 2 }}
  {{- else }}
  placeholder: ""
  {{- end }}
{{- end }}
