apiVersion: v1
kind: Service
metadata:
  name: {{ include "nivora.fullname" . }}-server
  labels:
    {{- include "nivora.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nivora.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
