apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nivora.fullname" . }}-worker
  labels:
    {{- include "nivora.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "nivora.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "nivora.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["worker", "--config", "/etc/nivora/worker.yaml"]
          {{- if or .Values.secret.create .Values.secret.existingName }}
          envFrom:
            - secretRef:
                name: {{ default (printf "%s-secret" (include "nivora.fullname" .)) .Values.secret.existingName }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/nivora
              readOnly: true
            - name: objectstore
              mountPath: /var/lib/nivora/objectstore
      volumes:
        - name: config
          configMap:
            name: {{ include "nivora.fullname" . }}-config
        - name: objectstore
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "nivora.fullname" . }}-objectstore
          {{- else }}
          emptyDir: {}
          {{- end }}
