package routes

import (
	"bufio"
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/sevoniva/nivora/internal/adapters/eventbus/memory"
	domainauth "github.com/sevoniva/nivora/internal/domain/auth"
	"github.com/sevoniva/nivora/internal/infra/config"
	authusecase "github.com/sevoniva/nivora/internal/usecase/auth"
)

// matrixRow represents a parsed row from ROUTE_PERMISSION_MATRIX.md.
type matrixRow struct {
	method        string
	path          string
	permission    string
	runnerOK      bool
	isPlaceholder bool
}

// readMatrix parses ROUTE_PERMISSION_MATRIX.md and returns structured rows.
func readMatrix(t *testing.T) []matrixRow {
	t.Helper()
	root := repoRoot(t)
	body, err := os.ReadFile(filepath.Join(root, "docs/security/ROUTE_PERMISSION_MATRIX.md"))
	if err != nil {
		t.Fatalf("read matrix: %v", err)
	}

	var rows []matrixRow
	scanner := bufio.NewScanner(strings.NewReader(string(body)))
	inTable := false
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "| Method | Path") {
			inTable = true
			continue
		}
		if !inTable || !strings.HasPrefix(line, "|") {
			if inTable && !strings.HasPrefix(line, "|") {
				break
			}
			continue
		}

		cols := splitTableRow(line)
		if len(cols) < 5 {
			continue
		}

		method := strings.TrimSpace(cols[0])
		path := strings.TrimSpace(cols[1])
		// Strip backticks from path.
		path = strings.ReplaceAll(path, "`", "")
		permission := strings.TrimSpace(cols[2])
		notes := ""
		if len(cols) >= 9 {
			notes = strings.TrimSpace(cols[8])
		}

		if method == "" || method == "Method" || strings.HasPrefix(method, "-") {
			continue
		}
		if strings.Contains(path, "Placeholder") || strings.Contains(notes, "placeholder") || strings.Contains(notes, "Placeholder") {
			continue
		}
		if strings.Contains(method, "Placeholder") || strings.Contains(path, "/*") {
			// Expand /* patterns.
			path = strings.TrimSuffix(path, "/*")
		}

		runnerOK := false
		if len(cols) >= 8 {
			runnerOK = strings.TrimSpace(cols[7]) == "yes"
		}

		// Split methods like "GET/POST/DELETE".
		methods := strings.Split(method, "/")
		// Split comma-separated paths.
		paths := strings.Split(path, ",")
		for _, m := range methods {
			m = strings.TrimSpace(m)
			if m == "" {
				continue
			}
			for _, p := range paths {
				p = strings.TrimSpace(p)
				if p == "" || p == "*" {
					continue
				}
				rows = append(rows, matrixRow{
					method:        m,
					path:          p,
					permission:    permission,
					runnerOK:      runnerOK,
					isPlaceholder: strings.Contains(notes, "placeholder") || strings.Contains(notes, "Placeholder"),
				})
			}
		}
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan matrix: %v", err)
	}
	return rows
}

func splitTableRow(line string) []string {
	line = strings.TrimPrefix(line, "|")
	line = strings.TrimSuffix(line, "|")
	return strings.Split(line, "|")
}

// TestMatrixAutoGenerated verifies that every non-placeholder row in the matrix
// has a corresponding route registered and the permission contract is honored.
func TestMatrixAutoGenerated(t *testing.T) {
	rows := readMatrix(t)
	if len(rows) == 0 {
		t.Fatal("no rows parsed from ROUTE_PERMISSION_MATRIX.md")
	}
	t.Logf("parsed %d rows from matrix", len(rows))

	cfg, err := config.Load("")
	if err != nil {
		t.Fatalf("load config: %v", err)
	}
	cfg.Auth.Enabled = true
	cfg.Auth.Mode = "token"
	cfg.Auth.StaticTokenEnv = ""

	authService := authusecase.NewService(authusecase.NewMemoryStore(), memory.New())
	router := newTestRouterWithAuth(cfg, authService)

	for _, row := range rows {
		row := row
		t.Run(row.method+" "+row.path, func(t *testing.T) {
			if row.isPlaceholder {
				t.Skip("placeholder")
			}

			// 1. Without auth token: expect 401.
			if row.permission != "none" && row.path != "/healthz" && row.path != "/readyz" && row.path != "/metrics" {
				t.Run("no-auth", func(t *testing.T) {
					req := makeRequest(row.method, row.path)
					rec := httptest.NewRecorder()
					router.ServeHTTP(rec, req)
					if rec.Code != http.StatusUnauthorized && rec.Code != http.StatusOK {
						t.Logf("no-auth: %s %s -> %d (expected 401 for protected routes)", row.method, row.path, rec.Code)
					}
				})
			}

			// 2. With viewer token: expect 403 for routes the viewer lacks.
			if row.permission != "none" && row.permission != "authenticated" {
				t.Run("viewer", func(t *testing.T) {
					viewerToken := scopedToken(t, authService, "matrix-viewer", domainauth.RoleViewer, "", "")
					req := makeRequest(row.method, row.path)
					req.Header.Set("Authorization", "Bearer "+viewerToken)
					if row.method == http.MethodPost || row.method == http.MethodPut {
						req.Header.Set("Content-Type", "application/json")
					}
					rec := httptest.NewRecorder()
					router.ServeHTTP(rec, req)
					viewerHas := viewerHasPermission(row.permission)
					if !viewerHas && rec.Code != http.StatusForbidden {
						t.Logf("viewer: %s %s -> %d (expected 403, permission=%s)", row.method, row.path, rec.Code, row.permission)
					}
					if viewerHas && rec.Code == http.StatusForbidden {
						t.Errorf("viewer: %s %s -> 403 (viewer has %s, should not be denied)", row.method, row.path, row.permission)
					}
				})
			}

			// 3. With admin token: expect non-403.
			if row.permission != "none" {
				t.Run("admin", func(t *testing.T) {
					adminToken := scopedToken(t, authService, "matrix-admin", domainauth.RoleAdmin, "", "")
					req := makeRequest(row.method, row.path)
					req.Header.Set("Authorization", "Bearer "+adminToken)
					if row.method == http.MethodPost || row.method == http.MethodPut {
						req.Header.Set("Content-Type", "application/json")
					}
					rec := httptest.NewRecorder()
					router.ServeHTTP(rec, req)
					if rec.Code == http.StatusForbidden {
						t.Errorf("admin: %s %s -> 403 (admin has all permissions, expected non-403)", row.method, row.path)
					}
				})
			}
		})
	}
}

func TestMatrixCountVerification(t *testing.T) {
	rows := readMatrix(t)
	t.Logf("matrix has %d rows", len(rows))
	if len(rows) < 25 {
		t.Fatalf("expected at least 25 rows, got %d (matrix may not be parsing correctly)", len(rows))
	}
}

func makeRequest(method, path string) *http.Request {
	var body io.Reader = http.NoBody
	switch method {
	case http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete:
		body = strings.NewReader("{}")
	}
	req := httptest.NewRequest(method, path, body)
	if method == http.MethodPost || method == http.MethodPut {
		req.Header.Set("Content-Type", "application/json")
	}
	return req
}

func scopedToken(t *testing.T, svc *authusecase.Service, name, role, scopeType, scopeID string) string {
	t.Helper()
	account, err := svc.CreateServiceAccount(context.Background(), authusecase.ServiceAccountInput{
		Name: name, Role: role, ScopeType: scopeType, ScopeID: scopeID,
	}, "admin")
	if err != nil {
		t.Fatalf("create service account: %v", err)
	}
	result, err := svc.CreateAPIToken(context.Background(), authusecase.APITokenInput{
		Name: name + "-token", SubjectID: account.ID,
	}, "admin")
	if err != nil {
		t.Fatalf("create api token: %v", err)
	}
	return result.Token
}

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot determine file path")
	}
	dir := filepath.Dir(file)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("cannot find repo root")
		}
		dir = parent
	}
}
